# Generated by Django 5.0.2 on 2024-02-21 12:14

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uav_', '0004_uav_description_alter_uav_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rental_end_date', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 12, 14, 10, 54773, tzinfo=datetime.timezone.utc))),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uav_.uav')),
            ],
        ),
    ]
