# Generated by Django 5.0.2 on 2024-02-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav_', '0002_alter_uav_is_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='image',
            field=models.CharField(default='', max_length=50, verbose_name='Image Path'),
            preserve_default=False,
        ),
    ]
