# Generated by Django 5.0.2 on 2024-02-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100, verbose_name='Branch')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('weight', models.FloatField(max_length=10, verbose_name='Weight')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('monthly_fee', models.FloatField(max_length=10, verbose_name='Monthly Fee')),
            ],
        ),
    ]
